[workspace]
resolver = "2"
members = ["crates/syntax"]

#[package]
#name = "slsp"
#version = "0.1.0"
#edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

#[dependencies]
#oxc_allocator = "0.13.1"
#rowan = "0.15.15"
